# -*- coding: utf-8 -*-
"""create_calendar

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10Lb83VSNyP5ikf0FuRkxLDECuAyhdUM3
"""

def create_calendar(day : str, year : int):
  """

  """
  days = ['Lundi','Mardi','Mercredi','Jeudi','Vendredi','Samedi','Dimanche']
  months = ['Janvier', 'Février', 'Mars', 'Avril', 'Mai', 'Juin','Juillet', 'Aout', 'Septembre', 'Octobre', 'Novembre', 'Décembre']
  nb_day_per_month = [31,28,31,30,31,30,31,31,30,31,30,31]
  calendar = []
  day_index = days.index(day)
  for i,month in enumerate(months):
    if year % 4 == 0:
      if year % 100 == 0 & year % 400 != 0:
        print('exception, pas bissextile')
      else:
        nb_day_per_month[1]+=1

    for j in range(nb_day_per_month[i]):
      calendar.append([days[day_index],j+1,month,year])
      if day_index<6:
        day_index += 1
      else:
        day_index = 0
  return calendar


calendar = create_calendar('Lundi',2024)

calendar